#!/bin/bash
#
# Reload cross-reference for .c and .h files using ctags and cscope
#

set -e

if [[ $1 == '' ]]; then
  echo "error: enter a path to scan .{c,cpp,h} files"
  exit 1
fi

CODE="$(readlink -e $1)"
csFILES=cscope.files

find ${CODE} -type f -not -iwholename '*.git*' -print \
  | grep -E '\.(c|h)$' > ${CODE}/${csFILES}

# Check man cscope for the meaning of each option
cscope -u -b -q -i ${CODE}/${csFILES}

# Check man ctags for the meaning of each option and run:
# ctags --list-kinds=c, for the meaning of each letter
ctags \
  --c-kinds=+defgmstuvx \
  --file-scope=no \
  --if0=no \
  -L ${CODE}/${csFILES}

