# shellcheck disable=SC2148
# Will be loaded in login shells after .zshenv and .zprofile

# Execute code in the background to not affect the current session
(
  setopt LOCAL_OPTIONS EXTENDED_GLOB
  autoload -U zrecompile

  # zrecompile -pq ${ZDOTDIR}/p10k.zsh
  zrecompile -pq ${ZDOTDIR}/zprofile
  # zrecompile -pq ${ZDOTDIR}/.zshenv

  # recompile all zsh or sh
  for f in "${ZDOTDIR}"/zsh-config/*.*sh; do
    zrecompile -pq "${f}"
  done
) &!

# vim:set ft=zsh ts=2 sw=2 et:
