# shellcheck disable=SC2148
# Similar to .zlogin but will be sourced before .zshrc
#
# Both .zprofile and .zshrc are skipped in non-login non-interactive shells
#
# Declares environment variables in .zprofile and uses .zshenv to source
# .zprofile. This way, non-login non-interactive shells will receive proper
# variable initialisations

# Avoid using .zshrc as it slower than .zprofile

#
# Paths
#
[[ -n "$ZPROFRC" ]] && zmodload zsh/zprof

#
# utility -> plugins-settings -> antidote-init -> extensions
#
for e in "${ZDOTDIR}"/zsh-config/*.zsh; do
  # shellcheck disable=SC1090
  source "${e}"
done

# done profiling
[[ -n "$ZPROFRC" ]] && zprof

# cleanup
[[ -n "$ZPROFRC" ]] && unset ZPROFRC

# vim:ft=zsh ts=2 sw=2 et:
