require('global')
require('autocmds')
require('backup')
require('mappings')
require('colors-ui')

require('plugins.packer')
require('plugins')
require('plugins.peekup')
require('plugins.barbar')
require('plugins.indent-blankline')
require('plugins.nerd-commenter')
require('plugins.formatter')
require('plugins.lualine')
require('plugins.nvim-tree')
require('plugins.suda')
require('plugins.barbar')
require('plugins.vim-better-whitespace')
-- require('plugins.snap')
