# Tool-specific environment variables (XDG relocations)
set -gx ANDROID_USER_HOME $XDG_DATA_HOME/android
set -gx RUSTUP_HOME $XDG_DATA_HOME/rustup
set -gx CARGO_HOME $XDG_DATA_HOME/cargo
set -gx GOPATH $XDG_DATA_HOME/go
set -gx GTK2_RC_FILES $XDG_CONFIG_HOME/gtk-2.0/gtkrc
set -gx XCURSOR_PATH /usr/share/icons:$XDG_DATA_HOME/icons
set -gx IPYTHONDIR $XDG_CONFIG_HOME/ipython
set -gx TERMINFO $XDG_DATA_HOME/terminfo
set -gx TERMINFO_DIRS $XDG_DATA_HOME/terminfo:/usr/share/terminfo
set -gx PARALLEL_HOME $XDG_CONFIG_HOME/parallel
set -gx PASSWORD_STORE_DIR $XDG_DATA_HOME/pass
set -gx RECOLL_CONFDIR $XDG_CONFIG_HOME/recoll
set -gx W3M_DIR $XDG_DATA_HOME/w3m
set -gx XINITRC $XDG_CONFIG_HOME/X11/xinitrc
set -gx ERRFILE $XDG_CACHE_HOME/X11/xsession-errors
set -gx XAUTHORITY $XDG_RUNTIME_DIR/Xauthority
set -gx NPM_CONFIG_USERCONFIG $XDG_CONFIG_HOME/npm/npmrc
set -gx PRE_COMMIT_COLOR never
set -gx SUPPRESS_BOLTDB_WARNING yes
set -gx npm_config_prefix $HOME/.local
