#!/bin/bash

mkdir -p /tmp/mytpm1
swtpm_setup --tpmstate dir:///tmp/mytpm1 --tpm2 --pcr-banks sha256
swtpm socket --tpmstate dir=/tmp/mytpm1 --ctrl type=unixio,path=/tmp/mytpm1/swtpm-sock --log level=0 --tpm2 -t -d
qemu-system-aarch64 \
    -machine virt,secure=on \
    -nographic \
    -cpu cortex-a57 \
    -m 1G \
    -bios u-boot.bin\
    -device virtio-rng-device \
    -chardev socket,id=chrtpm,path=/tmp/mytpm1/swtpm-sock -tpmdev emulator,id=tpm0,chardev=chrtpm -device tpm-tis-device,tpmdev=tpm0 \
    -nic user,model=virtio-net-pci \
    -drive id=disk1,file=$HOME/tmp/disk.img,if=none,format=raw -device virtio-blk-device,drive=disk1
    "$@"
