#!/bin/bash

if (command -v chezmoi > /dev/null 2>&1); then
  chezmoi managed -x dirs |
    rg -F "$1" |
    sed -ne 's/.*/\/home\/'"$USER"'\/&/p' |
    tr '\n' '\0' |
    xargs -0ro chezmoi edit --apply
else
  print 'zsh chezmoi plugin: chezmoi not found...' >&2
fi
