#!/bin/bash

mkdir -p /tmp/mytpm1; swtpm_setup --tpmstate dir:///tmp/mytpm1 --tpm2 --pcr-banks sha256; swtpm socket --tpmstate dir=/tmp/mytpm1 --ctrl type=unixio,path=/tmp/mytpm1/swtpm-sock --log level=0 --tpm2 -t -d; qemu-system-aarch64 -machine virt,secure=on -nographic -cpu cortex-a57 -bios u-boot.bin -device virtio-rng-device -m 1G -chardev socket,id=chrtpm,path=/tmp/mytpm1/swtpm-sock -tpmdev emulator,id=tpm0,chardev=chrtpm -device tpm-tis-device,tpmdev=tpm0 -nic user,model=virtio-net-pci "$@"
