#!/bin/bash

set -e

TOP_LEVEL=$(git rev-parse --show-toplevel)

if [ ! -d "$TOP_LEVEL/halon-src" ]; then
    echo "error: No a Halon repo"
    exit 1
fi

DIR_TEMP=$(mktemp --directory /ws/"$USER"/halon-build-dirs.XXXXX)

if [[ -d "$DIR_TEMP" ]]; then
    mv build* "$DIR_TEMP/"
fi

for d in "$DIR_TEMP"/build*; do
    ts rm -rf "$d";
done

if [[ -d "$DIR_TEMP" ]]; then
    rmdir "$DIR_TEMP"
fi
