#!/bin/bash

if (command -v chezmoi > /dev/null 2>&1); then
  chezmoi managed -x dirs |
    sed -ne 's/.*/\/home\/'"$USER"'\/&/p' |
    fzf --multi --ansi --height=90% --info=inline --no-separator --layout=reverse |
    tr '\n' '\0' |
    xargs -0ro chezmoi edit --apply
else
  print 'zsh chezmoi plugin: chezmoi not found...' >&2
fi
