#!/bin/bash -
#===============================================================================
#
#          FILE: t.sh
#
#         USAGE: ./t.sh
#
#   DESCRIPTION: 
#
#       OPTIONS: ---
#  REQUIREMENTS: ---
#          BUGS: ---
#         NOTES: ---
#        AUTHOR: YOUR NAME (), 
#  ORGANIZATION: 
#       CREATED: 03/28/2020 11:19:07 AM
#      REVISION:  ---
#===============================================================================

set -o nounset                                  # Treat unset variables as an error

diff <(cat $1 | sort) <(cat $2 | sort) | awk '/^<.*(=|Linux)/ { $1=""; print }'
diff <(cat $1 | sort) <(cat $2 | sort) | awk '/^>.*(=|Linux)/ { $1=""; print }'
