#!/bin/bash

echo "Backup work"
rsync -a --delete --exclude='*/build/' ~/repos/work /run/media/tiamarin/JETM_230G

echo "Backup thunderbird"
rsync -a --delete ~/.thunderbird /run/media/tiamarin/JETM_230G

echo "Backup Cursor"
rsync -a --delete ~/.cursor /run/media/tiamarin/JETM_230G
rsync -a --delete ~/.config/Cursor /run/media/tiamarin/JETM_230G/.config/
