#!/bin/bash

set -Ee

trim() {
  local var="$*"
  # remove leading whitespace characters
  var="${var#"${var%%[![:space:]]*}"}"
  # remove trailing whitespace characters
  var="${var%"${var##*[![:space:]]}"}"
  echo "$var"
}

create-branch() {
  local project=${1:-trs}
  local jira
  local default_branch
  default_branch=$(git remote show origin | grep -oP 'HEAD branch: \K.*')

  jira=$(jira-terminal list -M -p "${project}" \
    -S "Open" -S "In Progress" -S "Todo" -S "Review" \
    -d key,summary | fzf)
  local branch
  branch=$(echo "${jira}" | awk -F'|' '{print $1}')

  branch=$(trim "${branch}")

  local summary
  summary=$(echo "${jira}" | awk -F'|' '{print $2}')

  summary=$(trim "${summary}")

  if [[ -n ${branch} ]]; then
    git checkout -b "${branch}" "${default_branch}"
    git commit --allow-empty -m "${summary}"
  fi
}

create-branch "$@"

# vim:set ts=2 sw=2 et:
