#!/bin/bash

set -e

# Avoid to reenconde again
check-completed-format() {
  if [ -f .DONE_ENCODE ]; then
    echo 2>&1 "error: all files were formated"
    exit 1
  fi
}

# check for exist program
check-prog() {
  if ( ! command -v "$1" > /dev/null 2>&1 ); then
    echo 2>&1 "error: must install $1"
  fi
}

# set the subtitle to copy in mkv video file
do-sub() {
  # remove extension
  local dirfile
  dirfile=$(dirname -- "$1")

  local filename
  filename=$(basename -- "$1")
  local newfile="${dirfile}/${filename%.*}"

  local temp

  if [ -f "${newfile}.srt" ]; then
    temp="${newfile}.srt"
  elif [ -f "${newfile}_en.srt" ]; then
    temp="${newfile}_en.srt"
  elif [ -f "${newfile}.en.srt" ]; then
    temp="${newfile}.en.srt"
  elif [ -f "${newfile}_eng.srt" ]; then
    temp="${newfile}_eng.srt"
  elif [ -f "${newfile}.eng.srt" ]; then
    temp="${newfile}.eng.srt"
  fi

  if [ ! -f "${temp}" ]; then
    echo 2>&1 "error: no subtitle file"
    exit 1
  fi

  export subtitle="${temp}"
}

# create stage directory
do-stage() {
  if [ ! -d "$1/stage" ]; then
    mkdir "$1/stage" || exit 1
  fi
}

# choose the codec
set-video-codec() {
  local temp

  # extract video format
  codec=$(mediainfo --Inform='Video;%Format%' "$1")

  # AVC = x264, HEVC = x265
  if [[ "${codec}" == "AVC" ]]; then
    temp="x264"
  else
    temp="x265"
  fi

  temp="x265"
  export encoder="${temp}"
}

#
# start
#
check-prog HandBrakeCLI
check-prog mediainfo

#
# Input
#
origfile="$1"

#
# Output
#
dirfile=$(dirname -- "$1")
filename=$(basename -- "$1")
output_dir="${dirfile}/stage"
# Without extension
filename="${filename%.*}"
output="${output_dir}/${filename}.mkv"

# do-sub "${origfile}"
do-stage "${dirfile}"
set-video-codec "${origfile}"

# Recommended settings for x264 and x265 encoders:
#
# RF 18-22 for 480p/576p SD (Standard Definition)
# RF 19-23 for 720p      HD (High Definition)
# RF 20-24 for 1080p    FHD (Full High Definition)
# RF 22-28 for 2160p 4K UHD (Ultra High Definition)
#
# 22 is your go-to number in "Constant Quality" if you want low file size by ok
# quality. Use 23 or even 24 if you really need a low file size, 21 if you are
# looking for the best mix of quality and low files size (i.e. low file size is
# important, but not your primary goal).
#
# Resolution and Bitrate:
#  480p    848x480   410 kbps
#  720p   1280x720   920 kbps or 800
# 1080p  1920x1080  1600 kbps or 2k

# Typical video resolutions:
#
# --width 854 --height 480
# --width 1280 --height 720
# --width 1920 --height 1080
#
# Subtitle seems doesn't work well with handbrake
#
# --srt-file "${subtitle}" \
# --srt-lang eng \
# --srt-default 1 \
#
# --stop-at duration:300 \
# audio bitrate
# --ab 256

# run handbrake
HandBrakeCLI \
  --encoder "${encoder}" \
  --format av_mkv \
  --quality 22 \
  --aencoder copy \
  --input "${origfile}" \
  --output "${output}"

# Reduce size to 720p
# HandBrakeCLI \
  # --encoder "${encoder}" \
  # --width 1280 --height 720 \
  # --input "${origfile}" \
  # --output "${output}"

# Embeded subtitle inside of mkv
# filename=$(basename -- "${origfile}")
# extension="${filename##*.}"
# filename="${filename%.*}"
# output_sub="${output_dir}/${filename}_sub.${extension}"
#
# check-prog mkvmerge
# mkvmerge \
  # --output "${output_sub}" \
  # --language 0:eng \
  # --track-name 0:English "${subtitle}" \
  # "${output}"

# vim:set ft=sh ts=2 sw=2 et:
