# All SpaceVim option below [option] section
[options]
  # set spacevim theme. by default colorscheme layer is not loaded,
  # if you want to use more colorscheme, please load the colorscheme
  # layer
  colorscheme = "onedark"
  background = "dark"
  guifont = 'Input\ Mono\ Narrow\ Semi-Condensed\ 11'
  max_column = 80
  default_indent = 4

  # Disable guicolors in basic mode, many terminal do not support 24bit
  # true colors
  enable_guicolors = true

  # Disable statusline separator, if you want to use other value, please
  # install nerd fonts
  statusline_separator = "arrow"
  statusline_inactive_separator = "arrow"
  buffer_index_type = 4

  # Display file type icon on the tabline, If you do not have nerd fonts
  # installed, please change the value to false
  enable_tabline_filetype_icon = true

  # Display current mode text on statusline, by default It is disabled,
  # only color will be changed when switch modes.
  enable_statusline_display_mode = false

  bootstrap_after = "spacevim_after#after"
  bootstrap_before = "spacevim_before#before"

#
# Layers
#

# Enable autocomplete layer
[[layers]]
  name = 'autocomplete'
  auto-completion-return-key-behavior = "complete"
  auto-completion-tab-key-behavior = "smart"

[[layers]]
  name = 'shell'
  default_position = 'top'
  default_height = 30

[[layers]]
  name = 'VersionControl'

[[layers]]
  name = 'git'

[[layers]]
  name = 'fzf'

[[layers]]
  name = 'sudo'

[[layers]]
  name = 'tmux'

[[layers]]
  name = 'format'

[[layers]]
  name = 'checkers'

[[layers]]
  name = 'lang#c'

[[layers]]
  name = 'lang#sh'

[[layers]]
  name = 'lsp'
  filetypes = [
    "c",
    "sh"
  ]

#
# Plugins
#

[[custom_plugins]]
  name = "joshdick/onedark.vim"
  loadconf = 1
  merged = 0

[[custom_plugins]]
  name = 'tpope/vim-eunuch'

[[custom_plugins]]
  name = 'ConradIrwin/vim-bracketed-paste'

[[custom_plugins]]
  name = 'jetm/vim-bitbake'

[[custom_plugins]]
  name = 'Yggdroot/indentLine'
  merged = 0

[[custom_plugins]]
  name = "sheerun/vim-polyglot"
  merge = 0
  # if = "!index(['markdown'],&filetype)"

# These are 
# [[custom_plugins]]
  # name = 'octol/vim-cpp-enhanced-highlight'
  # on_ft = 'c'

# Vim syntax highlighting for c, bison, flex
# [[custom_plugins]]
  # name = 'justinmk/vim-syntax-extra'
