theme_location = ["~/.config/walker/themes"]
force_keyboard_focus = true

[providers]
default = [
  "desktopapplications",
]

[keybinds]
resume_last_query = ["ctrl r"]
quick_activate = []

[providers.desktopapplications]
default = "start"
history = true
show_sub_when_single = false
prioritize_new = false
launch_prefix = "uwsm app -- "
remove_history = ["ctrl h"]
start = "Return"
start_keep_open = "shift Return"
toggle_pin = ["ctrl p"]
